site_name: Mist VPN
site_url: https://mistwork.github.io/mkdocs-mistvpn-docs/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
