site_name: Mist VPN
site_url: https://mistwork.github.io/mkdocs-mistvpn-docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - md_in_html

nav:
  - Как подключиться?: connect.md
  - Предупреждение: warning.md

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Тёмная тема
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: light green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Светлая тема
  features:
    - navigation.instant

extra:
  generator: false

copyright: Made for Mist VPN with love <3

